SHOW_SLACK_BADGE: "true"
JUPYTER_NOTEBOOKS: "true"
JUPYTER_NOTEBOOKS_URL: "//{your-cenit-jupyter-notebooks}.herokuapp.com"
GITHUB_OAUTH_TOKEN: "{GITHUB_OAUTH_TOKEN}"
DB_PROD: "{DB_PROD}"
OAUTH_TOKEN_END_POINT: "embedded"
RELIC_LICENSE_KEY: "{RELIC_LICENSE_KEY}"
GOOGLE_ANALYTIC_ID: "{GOOGLE_ANALYTIC_ID}"
PORTAL_URL: 'https://cenit-portal.herokuapp.com'
DOCS_URL: 'https://cenit-io.github.io'
API_DOC_URL: 'https://cenit-io.github.io'
OPEN_ID_CLIENT_ID: "{OPEN_ID_CLIENT_ID}"
OPEN_ID_CLIENT_SECRET: "{OPEN_ID_CLIENT_SECRET}"
OPEN_ID_AUTH_URL: "https://cenit.io/app/open_id/sign_in"
OPEN_ID_REDIRECT_URI: "https://cenit.io/users/sign_in"
OPEN_ID_TOKEN_URL: "https://cenit.io/app/open_id/sign_in/token"
EXCLUDED_ACTIONS: simple_share bulk_share simple_cross_share bulk_cross_share build_gem bulk_pull
RABBITMQ_BIGWIG_TX_URL: "{RABBITMQ_BIGWIG_TX_URL}"
NOTIFIER_EMAIL: "{NOTIFIER_EMAIL}"
EXCEPTION_RECIPIENTS: "{List of emails}"
RABBIT_MQ_USER: "{RABBIT_MQ_USER}"
RABBIT_MQ_PASSWORD: "{RABBIT_MQ_PASSWORD}"

# AMAZON SIMPLE STORAGE SERVICE.
AWS_ACCESS_KEY_ID: "{AWSS3 Access ID}"
AWS_SECRET_ACCESS_KEY: "{AWSS3 Access Key}"

# CenitIO slug of application to manager plans, customers and subscriptions.
SUBSCRIPTIONS_APP: "cenit-io-subscriptions"
